octokit/webhooks.net

README.md

docs: update readme with correct package name

---

.github/release-drafter.yml

fix: prefix release drafts with 'v'

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
CONTRIBUTING.md
Directory.Build.props
README.md

This repository previously lived under my personal GitHub account. Now that it is under to octokit organization all references need to be updated.

chore: update all repository references

---

global.json

`latestMajor` allowed newer versions, like .NET 6

chore: update global.json to target .NET 5

---

src/Octokit.Webhooks/Converter/DateTimeOffsetConverter.cs
src/Octokit.Webhooks/Converter/NullableDateTimeOffsetConverter.cs
test/Octokit.Webhooks.Test/Converter/DateTimeOffsetConverterTests.cs
test/Octokit.Webhooks.Test/Converter/NullableDateTimeOffsetConverterTests.cs
test/Octokit.Webhooks.Test/WebhookEventProcessorTests.cs

test: add tests for datetimeoffset converters

---

src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs

This afternoon I migrated from [Terrajobst.GitHubEvents.AspNetCore](https://www.nuget.org/packages/Terrajobst.GitHubEvents.AspNetCore/) to this library, and have since observed that my application is now failing to handle various webhooks with an HTTP 500 error. They seem to involve `check_run` and some `pull_request` events.
Unfortunately, I don't know _why_ they are failing because exceptions caught by the HTTP endpoint are not logged, they're just swallowed.
This PR adds equivalent logging to the endpoint as the endpoint in Terrajobst.GitHubEvents.AspNetCore has ([code](https://github.com/terrajobst/Terrajobst.GitHubEvents/blob/cb86100c783373e198cefb1ed7e92526a44833b0/src/Terrajobst.GitHubEvents.AspNetCore/GitHubEventsExtensions.cs#L20-L61)), making it easier to diagnose payloads that …

Add logging to HTTP endpoint

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
Directory.Build.props
dotnet-tools.json
test/Directory.Build.props

Bump versions for:
- dotnet packages
- Cake
- GitHub Actions

chore: bump versions

---

src/Octokit.Webhooks/Models/CheckRunEvent/CheckRunStatus.cs
src/Octokit.Webhooks/Models/DeploymentStatusEvent/DeploymentStatusState.cs
src/Octokit.Webhooks/Models/WorkflowRunStatus.cs

Adds the `waiting` value to the `CheckRunStatus`, `DeploymentStatusState`, and `WorkflowRunStatus` enumerations.
Here's an example of the relevant part a webhook payload I received that had this status:
<details>
<summary>deployment_status payload</summary>
```json
{
"deployment_status": {
"url": "https://api.github.com/repos/martincostello/SignInWithAppleSample/deployments/534555140/statuses/962858309",
"id": 962858309,
"node_id": "DES_kwDOC2Wnd845ZA1F",
"state": "waiting",
"creator": {
"login": "martincostello",
"id": 1439341,
"node_id": "MDQ6VXNlcjE0MzkzNDE=",
"avatar_url": "https://avatars.githubusercontent.com/u/1439341?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/martincostello",
"html_url": "https://github.com/martincostello",
"followers_url": …
```

fix: add waiting deployment status state

---

src/Octokit.Webhooks/Events/DeploymentEvent.cs
src/Octokit.Webhooks/Events/DeploymentStatusEvent.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentCheckRun.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentCheckRunConclusion.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentCheckRunStatus.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentWorkflowRun.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentWorkflowRunConclusion.cs
src/Octokit.Webhooks/Models/DeploymentEvent/DeploymentWorkflowRunStatus.cs
src/Octokit.Webhooks/Models/DeploymentStatusEvent/DeploymentStatus.cs
src/Octokit.Webhooks/Models/WorkflowRun.cs

- Add missing properties to `DeploymentStatusEvent`
- Add missing properties to `WorkflowRun`
~I've made an assumption here that the properties for check suite and workflows are nullable.~ https://github.com/octokit/webhooks.net/pull/55#discussion_r837234585
~I've also omitted the missing `actor` and `triggering_actor` properties at this point as I'm not sure what the type should be with respect to the schema and I couldn't see an obvious existing type for it.~
Resolves #54.

feat: Add missing deployment_status properties

---

src/Octokit.Webhooks/Converter/WebhookConverter.cs

Only scan the types in the `Octokit.Webhooks` assembly for the `[WebhookActionType]`, rather than all assemblies in the current AppDomain.
`WebhookActionTypeAttribute` is internal and not inherited, and `InternalsVisibleToAttribute` isn't used, so it _should_ not be possible to be present on any types in any other assembly (assuming I've understood what's going on correctly).
I found this via an occasional test failure I'm getting in the CI for a project where I'm using Octokit.Webhooks.AspNetCore because the webhook converter is trying to scan dynamic assemblies created by Moq in my unit tests.
```
[2022-04-12 12:19:22Z] fail: Octokit.Webhooks.WebhookEventProcessor[0]
Exception processing GitHub event.
System.Reflection.TargetInvocationException: Exception has been thrown by the target …
```

Only scan Octokit.Webhooks for [WebhookActionType]

---

global.json
samples/AspNetCore/AspNetCore.csproj
src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs
src/Octokit.Webhooks.AspNetCore/Octokit.Webhooks.AspNetCore.csproj
src/Octokit.Webhooks/Octokit.Webhooks.csproj
test/Octokit.Webhooks.Test/Octokit.Webhooks.Test.csproj
test/Octokit.Webhooks.TestUtils/Octokit.Webhooks.TestUtils.csproj

.NET 5 goes out of support on the 10th May 2022[^1]. This PR should be merged before then.
Closes #37
[^1]: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Upgrade to .NET 6.0

---

samples/AspNetCore/AspNetCore.csproj
samples/AspNetCore/Startup.cs
src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs

With #37 completed, there are some new APIs/features for ASP.NET Core 6 that can be used.
* Use the new "one-shot" `HMACSHA256.HashData()` method to remove need to allocate an object.
* Fix new CA1848 warnings by using the new [logging source generator](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator).
* Fix (or suppress) various compiler and IDE warnings. There's now only 3 if I build the solution locally (2x IDE0072 and 1x CA2201).

Use .NET 6 features

---

renovate.json

It's disabled at the organization level for Octokit because there is no overall maintainer. Specific projects within the Octokit organization, with maintainers, can enable it.

chore: explicitly enable renovate

---

build.cake

See https://github.com/cake-build/cake/issues/3341

chore: `DotNetCore*` commands are deprecated in favour of `DotNet*` commands

---

SECURITY.md

This adds a security policy to this repo so that if incidents occur then our users will be able to reach out to GitHub using the proper channels.

Creates SECURITY.md for GitHub owned repo compliance

---

renovate.json

The default setting for `ignorePaths` skips the projects under the `test` directory.

ci: set `ignorePaths` for renovate

---

src/Octokit.Webhooks/Models/PingEvent/HookType.cs

Add missing `App` value to `HookType`.
Looks like it's [missing from the schema](https://github.com/octokit/webhooks/blob/2bd8c0e7fff3d38a4a5669c4b52f4e05ba6bccf2/payload-schemas/api.github.com/ping/event.schema.json#L29), but I'm 99.9% sure that [this example](https://github.com/martincostello/costellobot/blob/420f9f4eeb78e5afa5da4e3fc3f32362e75ddf1f/tests/Costellobot.Tests/UITests.cs#L137-L164) from my GitHub App's tests [that now fail with the latest update](https://github.com/martincostello/costellobot/runs/7228744519?check_suite_focus=true#step:4:470) was adapted from the real webhook payload I received when I was developing it.
It would also make sense, because [the documentation mentions the app-specific property `app_id`](https://docs.github.com/en/developers/webhooks-and-events/we …

fix: Add App to HookType

---

Octokit.Webhooks.sln
README.md
samples/AzureFunctions/AzureFunctions.csproj
samples/AzureFunctions/MyWebhookEventProcessor.cs
samples/AzureFunctions/Program.cs
samples/AzureFunctions/host.json
samples/AzureFunctions/local.settings.json
src/Octokit.Webhooks.AzureFunctions/GitHubWebhooksHttpFunction.cs
src/Octokit.Webhooks.AzureFunctions/GitHubWebhooksOptions.cs
src/Octokit.Webhooks.AzureFunctions/GithubWebhookHostBuilderExtensions.cs
src/Octokit.Webhooks.AzureFunctions/Octokit.Webhooks.AzureFunctions.csproj

This adds the `Octokit.Webhooks.AzureFunctions` package, which allows for easy use of `Octokit.Webhooks` in Azure Functions projects. The package targets .NET 6.0 isolated Azure Functions[^1]
By adding the package to your project, an HTTP POST triggered function is registered under the `/api/github/webhooks` path.
This also includes an MVP sample project to show how to configure an Azure Functions project.
Closes #36
[^1]: https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

feat: add `octokit.webhooks.azurefunctions` library

---

src/Octokit.Webhooks/WebhookActionTypeAttribute.cs
src/Octokit.Webhooks/WebhookEventTypeAttribute.cs

This fixes the CA1852 analyzer warning

refactor: mark internal attributes as sealed

---

src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStepConclusion.cs

Resolves #169
----
When a workflow_job.completed with a `failed` conclusion event is deserialized it fails because steps can have `in_progress` and `queued` status which are not included in the WorkflowJobStepConclusion enums
* 
The `in_progress` & `queued`  status steps can be deserialized for a workflowflow completed event with a failed conclusion and steps that are in_progress or queued.
* 
* 
----
* N/A
- Dependencies/code cleanup: `Type: …

Add in_progress and queued to WorkflowJobStepConclusion enums

---

Directory.Build.targets

Resolves the deprecation warning from MinVer
```
warning MINVER1008: MinVerDefaultPreReleasePhase is deprecated and will be removed in the next major version. Use MinVerDefaultPreReleaseIdentifiers instead, with an additional "0" identifier. For example, if you are setting MinVerDefaultPreReleasePhase to "preview", set MinVerDefaultPreReleaseIdentifiers to "preview.0" instead.
```
----
* 
* 
* 
----
* N/A
- Dependencies/code cleanup: `Type: …

chore: resolve minver deprecation

---

src/Octokit.Webhooks/Events/PullRequest/PullRequestAction.cs
src/Octokit.Webhooks/Events/PullRequest/PullRequestActionValue.cs
src/Octokit.Webhooks/Events/PullRequest/PullRequestDemilestoned.cs
src/Octokit.Webhooks/Events/PullRequest/PullRequestMilestoned.cs
src/Octokit.Webhooks/WebhookEventProcessor.cs

Closes #223
----
* 
* 
* 
----
* N/A
----

feat: add `pull_request.{demilestoned, milestoned}` events

---

src/Octokit.Webhooks/Models/DeploymentStatusEvent/DeploymentStatusState.cs

Resolves #245
----
* The `"queued"` value in webhook payloads would be deserialized to `Unknown`.
* The `"queued"` value in webhook payloads would be deserialized to `Queued`.
N/A
----
* N/A
It's either a feature because it's new and being added, or it's a bug because it wasn't already. I've gone with feature.
----

feat: add DeploymentStatusState.Queued

---

src/Octokit.Webhooks/Converter/DateTimeOffsetConverter.cs
src/Octokit.Webhooks/Converter/NullableDateTimeOffsetConverter.cs
test/Octokit.Webhooks.Test/Converter/DateTimeOffsetConverterTests.cs
test/Octokit.Webhooks.Test/Converter/NullableDateTimeOffsetConverterTests.cs

Resolves #103 
* Calling `JsonSerializer.Serialize` for any webhook payloads that had `DateTimeOffset` properties would throw a `JsonException`
* Allows serialization of `DateTimeOffset` and `DateTimeOffset?` to ISO 8601 using [the round-trip format][1]
* 
----
* N/A
----
[1]: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier

feat: allow serialization of `DateTimeOffset`

---

src/Octokit.Webhooks/Models/CheckSuiteEvent/CheckSuiteConclusion.cs

Resolves #283
----
* Check suite conclusions for `action_required`, `startup_failure` and `skipped` fail to be parsed.
* Check suite conclusions for `action_required`, `startup_failure` and `skipped` can be parsed and represented in C#.
None.
----
* N/A

fix: Fix CheckSuiteConclusion enum

---

src/Octokit.Webhooks/WebhookEvent.cs

This is mostly to cover the case where we've incorrectly typed an event, or haven't updated quick enough to represent GitHub webhook changes.

feat: deserialize any additional data to a dictionary

---

src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStatus.cs

The `WorkflowJobStatus` enum is lacking the `Waiting`, which cases an exception.
```
[Parameter(Value = "waiting")]
Waiting,
```
```
System.AggregateException: An error occurred while writing to logger(s). (Value 'waiting' is not a valid 'WorkflowJobStatus' enum value.)  ---> System.ArgumentException: Value 'waiting' is not a valid 'WorkflowJobStatus' enum value.   
at Octokit.Webhooks.Extensions.StringEnum`1.ParseValue()   
at Octokit.Webhooks.Extensions.StringEnum`1.get_Value()   
at Octokit.Webhooks.Extensions.StringEnum`1.PrintMembers(StringBuilder builder)   
at Octokit.Webhooks.Extensions.StringEnum`1.ToString()   
at Octokit.Webhooks.Models.WorkflowJobEvent.WorkflowJob.PrintMembers(StringBuilder builder)   
at Octokit.Webhooks.Models.WorkflowJobEvent.WorkflowJob.ToString()   
at …
```

[fix]: Add missing "waiting" enum to WorkflowJobStatus.cs

---

.devcontainer/devcontainer.json
Directory.Build.props
global.json
samples/AspNetCore/MyWebhookEventProcessor.cs
samples/AzureFunctions/MyWebhookEventProcessor.cs
src/Octokit.Webhooks.AzureFunctions/GitHubWebhooksHttpFunction.cs
src/Octokit.Webhooks/Octokit.Webhooks.csproj
src/Octokit.Webhooks/WebhookActionTypeAttribute.cs
src/Octokit.Webhooks/WebhookEventTypeAttribute.cs

The packages are still published as targeting .NET 6, but this change requires .NET 8 to build the packages. This allows us to take advantage _some_ newer .NET features in a backwards compatible way.

chore(deps): upgrade to .net 8 sdk

---

src/Octokit.Webhooks/Models/PackageType.cs
src/Octokit.Webhooks/Models/PackageVersion.cs
src/Octokit.Webhooks/Models/PackageVersionNugetMetadata.cs

Resolves #462
Resolves #460 
----
* The value of Nuget **PackageType** is `nuget` (in lowercase)
* The type of **NugetMetatada** property of **PackageVersion** is `IDictionary<string, dynamic>?`
* The value of Nuget **PackageType** is now `NUGET` (in uppercase) according to the payload sent by GitHub Webhooks.
* The type of **NugetMetatada** property of **PackageVersion** is now `IEnumerable<PackageVersionNugetMetadata>?` according to the paylod sent by GitHub Webhooks and according to the [GitHub Webhooks Docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#package)
* Added **PackageVersionNugetMetadata** type for better binding **nuget_metadata** field of webhook according to the paylod sent by GitHub Webhooks and according to the [GitHub Webhooks …

Fix: Nuget PackageEvent

---

src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs

Allows additional configuration of endpoint. For example, allowing anonymous access for the endpoint for an app that otherwise requires a specific type of authentication: `app.MapGitHubWebhooks("/api/github/webhooks, githubWebhookSecret).AllowAnonymous()`
Resolves #476
----
If you have authentication on your entire app but you want to allow anonymous access to the GitHub webhook endpoint, there doesn't seem to be a way to do that currently.
The IEndpointConventionBuilder is available to users of the library, so they can configure any of the settings that you normally could for a `app.MapPost( ... )` call, including `AllowAnonymous()`.
----

feat: return IEndpointConventionBuilder from MapGitHubWebhooks to allow additional configuration of endpoint

---

.github/workflows/build.yml

All PR builds on this repo are currently failing because Actions dropped .NET 6 from its default runners. The long-term fix is to upgrade our .NET versions across all of our repositories, but this should allow our Dependabot upgrades to ship in the short-term.

Install .NET 6 in CI builds

---

.github/workflows/scorecard.yml
README.md

Add a workflow for [OpenSSF Scorecards](https://scorecard.dev/). This allows us to more easily follow the best security practices for open source packages.
----
* No insight into the scorecard result
* OpenSSF scorecard is on every push to `main`, and weekly on a schedule.
----

ci: add ossf scorecard workflow

---

src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJob.cs
src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStep.cs

Resolves #524 
----
* An inconsistent mix of `string` and `DateTimeOffset` for `*_at` fields.
* Use `DateTimeOffset` everywhere instead of `string`
----

Use `DateTimeOffset` everywhere instead of `string`

---

src/Octokit.Webhooks/Events/DeploymentProtectionRule/DeploymentProtectionRuleRequestedEvent.cs
src/Octokit.Webhooks/Events/DeploymentProtectionRuleEvent.cs

There is only one action, `requested`, for the `deployment_protection_rule` event. So we can't know which properties are common between different actions. Moving them all to the base, abstract, class makes the properties easier to access for now.
Resolves #546
----
* You need to cast `DeploymentProtectionRuleEvent` to `DeploymentProtectionRuleRequestedEvent`
* Common properties are available without a cast
----

fix: move common properties from `DeploymentProtectionRuleRequestedEvent` to `DeploymentProtectionRuleRequestedEvent`

---

src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs
src/Octokit.Webhooks.AspNetCore/GitHubWebhookOptions.cs

Currently, the secret is statically defined when registering the GitHub webhooks endpoint with `MapGitHubWebhooks`. But this means that the `secret` used to validate the webhooks signature is static for the lifetime of the application.
If, instead, we attempt to fetch the secret from `IOptionsMonitor<GitHubWebhookOptions>` it allows us to rotate the secret without restarting the application.
This is also implemented in a backwards compatible manner. If the `secret` parameter passed to `MapGitHubWebhooks` is `null`, but an `IOptionsMonitor<GitHubWebhookOptions>` instance has been registered, the secret will be fetched from there instead.
Closes #486
----
* The GitHub webhook validation secret is static for the lifetime of the application
* The GitHub webhook 
Please see our docs on …

feat: fetch secret from `IOptionsMonitor` if defined

---

src/Octokit.Webhooks/Converter/DateTimeOffsetConverter.cs
test/Octokit.Webhooks.Test/Converter/DateTimeOffsetConverterTests.cs

Use `long` instead of `int` to avoid an implicit conversion and the Y2038 bug.
Resolves #590.
----
* An implicit conversion from `int` to `long` occurs when creating a `DateTimeOffset` from a JSON number.
* Numeric timestamps beyond `2038-01-19T03:14:07Z` cannot be deserialized:
```text
System.Text.Json.JsonException : The JSON value could not be converted to System.DateTimeOffset. Path: $ | LineNumber: 0 | BytePositionInLine: 10.
---- System.FormatException : Either the JSON value is not in a supported format, or is out of bounds for an Int32.
ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, …
```

Use long for numeric dates

---

src/Octokit.Webhooks/Models/RepositoryRulesetEvent/RepositoryRuleset.cs
src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJob.cs
src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStep.cs

Resolves #595
----
* Some datetime types were incorrectly deserialized
* Datetime types are correctly serialized
----

fix: some datetime types should be nullable

---

.devcontainer/devcontainer.json
.github/workflows/build.yml
samples/AspNetCore/AspNetCore.csproj
samples/AzureFunctions/AzureFunctions.csproj
test/Octokit.Webhooks.AzureFunctions.Test/Octokit.Webhooks.AzureFunctions.Test.csproj
test/Octokit.Webhooks.Test/Octokit.Webhooks.Test.csproj
test/Octokit.Webhooks.TestUtils/Octokit.Webhooks.TestUtils.csproj

.NET 6 is now end-of-life. This change retargets sample and test projects to use .NET 9, while leaving the libraries targeting .NET 6.
----
* All projects target .NET 6
* Test and sample projects target .NET 9
No
----

target dotnet 9.0 for test and sample projects

---

src/Directory.Build.props
test/Directory.Build.props
test/Octokit.Webhooks.AzureFunctions.Test/Octokit.Webhooks.AzureFunctions.Test.csproj
test/Octokit.Webhooks.Test/Octokit.Webhooks.Test.csproj
test/Octokit.Webhooks.Test/WebhookEventProcessorTests.cs
test/Octokit.Webhooks.Test/WebhookEventProcessorTestsData.cs
test/Octokit.Webhooks.TestUtils/Octokit.Webhooks.TestUtils.csproj

Follow-up from #623 
----
* Using xunit v2
* Using xunit v3
----

chore(deps): migrate to xunit.v3

---

src/Octokit.Webhooks.AzureFunctions/GitHubWebhooksHttpFunction.cs

```
Error: /home/runner/work/webhooks.net/webhooks.net/src/Octokit.Webhooks.AzureFunctions/GitHubWebhooksHttpFunction.cs(54,49): error IDE0305: Collection initialization can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0305) [/home/runner/work/webhooks.net/webhooks.net/src/Octokit.Webhooks.AzureFunctions/Octokit.Webhooks.AzureFunctions.csproj]
```

fix ide0305

---

src/Directory.Build.props
src/Octokit.Webhooks.AspNetCore/Octokit.Webhooks.AspNetCore.csproj
src/Octokit.Webhooks.AzureFunctions/Octokit.Webhooks.AzureFunctions.csproj
src/Octokit.Webhooks/Octokit.Webhooks.csproj

Preparing for a major version bump I'm increasing the supported version of .NET from 6 to 8. This is inline with the new Octokit SDK
----
* .NET 6+ supported
* .NET 8+ supported
----

chore: bump from .net 6 to .net 8

---

README.md
samples/AspNetCore/MyWebhookEventProcessor.cs
samples/AzureFunctions/MyWebhookEventProcessor.cs
src/Octokit.Webhooks/WebhookEventProcessor.cs

----
* `WebhookEventProcessor` method signatures return `Task`
* `WebhookEventProcessor` method signatures return `ValueTask`
----

refactor: use `ValueTask` over `Task` where appropriate

---

src/Octokit.Webhooks/Models/AppPermissions.cs

Potential workaround for #745 
EDIT: confirmed fix.
----
* Not all properties under `AppPermissions` were using `StringEnum<TEnum>`
* Remaining properties under `AppPermissions` were using `StringEnum<TEnum>`
----

fix: migrate remaining `AppPermissions` to use `StringEnum<TEnum>`

---

src/Octokit.Webhooks/Extensions/StringEnum.cs
test/Octokit.Webhooks.Test/Extensions/StringEnumTests.cs
test/Octokit.Webhooks.Test/StringEnumTests.cs

Resolves #738 
----
* 
* 
----

Implement `IEquatable` for `StringEnum`
