- Directory.Build.targets
See: https://github.com/adamralph/minver#can-i-prefix-my-tag-names
> fix: set minver prefix

- README.md
Hi there, its me again 👋 
Realised I missed this in the initial changes included in #16 
Hopefully will make it slightly easier for people following the docs.
> Update readme to match new async interface

- src/Octokit.Webhooks/Models/SimplePullRequest.cs
> fix: automerge should be nullable in simplepullrequest

- src/Octokit.Webhooks/Models/AppEvent.cs
> fix: add repository_vulnerability_event

- src/Octokit.Webhooks/Models/PullRequestEvent/PullRequest.cs
- src/Octokit.Webhooks/Models/SimplePullRequest.cs
> fix: deserialize requested_reviewers

- Directory.Build.props
- src/Directory.Build.props
- src/Octokit.Webhooks/Octokit.Webhooks.csproj
- test/Directory.Build.props
- `Microsoft.SourceLink.GitHub` from `1.0.0` to `1.1.1`
- `Microsoft.NET.Test.Sdk` from `16.11.0` to `17.0.0`
- `Microsoft.VisualStudio.Threading.Analyzers` from `17.0.63` to `17.0.64`
- `JetBrains.Annotations` from `2021.2.0` to `2021.3.0`
- `Macross.Json.Extensions` from `2.0.0` to `2.2.0`
- `Microsoft.Extensions.Primitives` from `5.0.1` to `6.0.0`
> chore: update dependencies

- src/Octokit.Webhooks/WebhookEventProcessor.cs
> style: fix lint warnings in WebhookEventProcessor

- src/Octokit.Webhooks/Models/PullRequestAutoMerge.cs
- src/Octokit.Webhooks/Models/PullRequestEvent/PullRequest.cs
- src/Octokit.Webhooks/Models/SimplePullRequest.cs
It's not a boolean, but an object. See https://raw.githubusercontent.com/github/rest-api-description
> fix: correctly type auto_merge property

- .editorconfig
- src/Octokit.Webhooks/WebhookEventProcessor.cs
> fix: roslyn warnings

- Directory.Build.props
- src/Octokit.Webhooks/Octokit.Webhooks.csproj
- test/Directory.Build.props
> chore: dependency updates

- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemAction.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemActionValue.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemArchivedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemConvertedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemCreatedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemDeletedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemEditedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemReorderedEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2Item/ProjectsV2ItemRestoredEvent.cs
- src/Octokit.Webhooks/Events/ProjectsV2ItemEvent.cs
- src/Octokit.Webhooks/Models/ProjectsV2Item.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemContentType.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/Changes.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/ChangesArchivedAt.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/ChangesContentType.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/ChangesFieldValue.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/ChangesPreviousProjectsV2ItemNodeId.cs
- src/Octokit.Webhooks/Models/ProjectsV2ItemEvent/FieldType.cs
- src/Octokit.Webhooks/WebHookEventType.cs
- src/Octokit.Webhooks/WebhookEventProcessor.cs
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/archived.payload.json
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/converted.payload.json
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/created.payload.json
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/edited.payload.json
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/reordered.payload.json
- test/Octokit.Webhooks.Test/Resources/projects_v2_item/restored.payload.json
> feat: new `projects_v2_item` event

- renovate.json
> ci: enable renovate dependency dashboard

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
> ci: narrow github token permissions

- samples/AspNetCore/MyWebhookEventProcessor.cs
- samples/AspNetCore/Program.cs
- src/Octokit.Webhooks/Converter/WebhookConverter.cs
- src/Octokit.Webhooks/Events/DeploymentEvent.cs
- src/Octokit.Webhooks/Events/GithubAppAuthorizationEvent.cs
- src/Octokit.Webhooks/Events/OrganizationEvent.cs
- src/Octokit.Webhooks/Events/RegistryPackageEvent.cs
- src/Octokit.Webhooks/Models/App.cs
- src/Octokit.Webhooks/Models/CodeScanningAlertEvent/AlertRuleSeverity.cs
- src/Octokit.Webhooks/Models/Installation.cs
- src/Octokit.Webhooks/Models/PingEvent/Hook.cs
- src/Octokit.Webhooks/Models/ProjectCardEvent/Changes.cs
- src/Octokit.Webhooks/Models/RepositoryEvent/ChangesRepository.cs
- src/Octokit.Webhooks/Models/SecretScanningAlertEvent/AlertResolution.cs
- test/Octokit.Webhooks.Test/Converter/DateTimeOffsetConverterTests.cs
- test/Octokit.Webhooks.Test/Converter/NullableDateTimeOffsetConverterTests.cs
- test/Octokit.Webhooks.Test/WebhookEventProcessorTests.cs
Includes:
- Remove redundant initializer for nullable properties
- Use `var` in place of actual types
- Remove empty body for empty records
- Correct namespaces for `AlertRuleSeverity` and `AlertResolution`
- Remove unnecessary null check
- Use lambdas where possible
> refactor: ide refactor suggestions

- src/Octokit.Webhooks/Events/MergeGroupEvent.cs
> fix: mark mergegroupevent as abstract

- src/Octokit.Webhooks/Models/AppPermissions.cs
[octokit/webhooks@`0633a28` (#690)](https://github.com/octokit/webhooks/pull/690/commits/0633a289b7cafb7330e9171f276597d5ee2157ad)
> fix: add `blocking` to app permissions

- src/Octokit.Webhooks/Events/PullRequest/PullRequestAction.cs
- src/Octokit.Webhooks/Events/PullRequest/PullRequestActionValue.cs
- src/Octokit.Webhooks/Events/PullRequest/PullRequestDequeuedEvent.cs
- src/Octokit.Webhooks/Events/PullRequest/PullRequestQueuedEvent.cs
- src/Octokit.Webhooks/WebhookEventProcessor.cs
https://github.com/octokit/webhooks/commit/44b5c3c6aa56bb780b01f0af972942496c08a783
> feat: new `PullRequestQueued` and `PullRequestDequeued` events

- src/Octokit.Webhooks/Models/PullRequestReviewEvent/Review.cs
> fix: `submitted_at` can be null

- .github/workflows/codeql-analysis.yml
> ci: simplify and pin codeql workflow

- src/Octokit.Webhooks.AzureFunctions/GithubWebhookHostBuilderExtensions.cs
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0053
This warning is being flagged in the .NET 7 SDK upgrade #430
> refactor: fix IDE0053

- .github/PULL_REQUEST_TEMPLATE.md
- .github/pull_request_template.md
This PR adds our standardized PR templates.
> Add PR templates

- README.md
See https://github.com/badges/shields/issues/8671
----
* 
* 
* 
----
* N/A
----
> docs: fix badge url

- src/Octokit.Webhooks/WebhookEventProcessor.cs
- src/Octokit.Webhooks/WebhookHeaders.cs
> [CA1510] Use 'ArgumentNullException.ThrowIfNull' instead of explicitly throwing a new exception instance
----
* 
* 
* 
----
* N/A
----
> chore: resolve CA1510

- src/Octokit.Webhooks/Converter/DateTimeOffsetConverter.cs
- src/Octokit.Webhooks/Converter/WebhookConverter.cs
> [IDE0270] Null check can be simplified
----
* 
* 
* 
----
* N/A
----
> chore: fix IDE0270

- test/Octokit.Webhooks.Test/WebhookEventProcessorTests.cs
> [CA1859]: Use concrete types when possible for improved performance
----
* 
* 
* 
----
* N/A
----
> chore: fix CA1859

- src/Octokit.Webhooks/Events/InstallationTarget/InstallationTargetAction.cs
- src/Octokit.Webhooks/Events/InstallationTarget/InstallationTargetActionValue.cs
- src/Octokit.Webhooks/Events/InstallationTarget/InstallationTargetRenamedEvent.cs
- src/Octokit.Webhooks/Events/InstallationTargetEvent.cs
- src/Octokit.Webhooks/Models/InstallationTargetEvent/Changes.cs
- src/Octokit.Webhooks/Models/InstallationTargetEvent/ChangesLogin.cs
- src/Octokit.Webhooks/Models/InstallationTargetEvent/ChangesSlug.cs
- src/Octokit.Webhooks/WebHookEventType.cs
- src/Octokit.Webhooks/WebhookEventProcessor.cs
Types taken from https://github.com/octokit/webhooks/pull/767
----
* 
* 
* 
----
* N/A
----
> feat: add `installation_target` event

- Directory.Build.props
- src/Directory.Build.props
Closes #107
See https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile
----
* 
* 
* 
----
* N/A
----
> docs: include README in package

- src/Octokit.Webhooks/Converter/WebhookConverter.cs
> refactor: use newer C# features in `WebhookConverter`

- .github/workflows/add_to_octokit_project.yml
- .github/workflows/build.yml
- .github/workflows/stale.yaml
> ci: pin actions to hash

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yaml
> ci: set explicit permissions for all workflows

- samples/AspNetCore/Program.cs
- samples/AzureFunctions/Program.cs
----
Builds fail due to a false warning of CA1852[^1]. See https://github.com/dotnet/roslyn-analyzers/issues/6141
No build warnings
* 
----
* N/A
----
[^1]: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1852
> fix: CA1852 false warning

- test/Directory.Build.props
Reverts #321 #322
See https://github.com/moq/moq/issues/1372
> chore(deps): downgrade moq to 4.18.4

- src/Octokit.Webhooks/Models/AppEvent.cs
Resolves #383
----
- Value branch_protection_configuration was not covered by AppEvent enum
* branch_protection_configuration value was added to AppEvent enum
----
> fix: AppEvent branch_protection_configuration value

- .vscode/extensions.json
Suggest the [C# Dev Kit][1]
[1]: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit
> chore: add recommended vscode extensions

- .devcontainer/devcontainer.json
NOTE: The .NET 8 SDK devcontainer base images haven't been published yet
Closes #135
> chore: add devcontainer configuration

- src/Octokit.Webhooks.AspNetCore/GitHubWebhookOptions.cs
Resolves https://github.com/octokit/webhooks.net/pull/550#discussion_r1776161065
----
* `GitHubWebhookOptions` was not overridable 
* `GitHubWebhookOptions` can be overridden
- [] Tests for the changes have been added (for bug fixes / features)
----
> Unseal `GitHubWebhookOptions`

- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- global.json
- src/Octokit.Webhooks/Converter/StringEnumEnumerableConverter.cs
> chore(deps): upgrade to .net 9 sdk

- test/Directory.Build.props
- test/Octokit.Webhooks.AzureFunctions.Test/GithubWebhookHostBuilderExtensionsTests.cs
- test/Octokit.Webhooks.Test/Converter/DateTimeOffsetConverterTests.cs
- test/Octokit.Webhooks.Test/Converter/NullableDateTimeOffsetConverterTests.cs
- test/Octokit.Webhooks.Test/Converter/StringEnumConverterTests.cs
- test/Octokit.Webhooks.Test/Converter/StringEnumEnumerableConverterTests.cs
- test/Octokit.Webhooks.Test/Extensions/StringEnumTests.cs
- test/Octokit.Webhooks.Test/StringEnumTests.cs
- test/Octokit.Webhooks.Test/WebhookEventProcessorTests.cs
Resolves #720 
----
* Tests are using FluentAssertions
* Tests are using AwesomeAssertions
----
> #720: Migrate from FluentAssertions to AwesomeAssertions

- src/Octokit.Webhooks/Converter/StringEnumConverter.cs
- src/Octokit.Webhooks/Converter/StringEnumEnumerableConverter.cs
- src/Octokit.Webhooks/Extensions/StringEnum.cs
- test/Octokit.Webhooks.Test/Extensions/StringEnumTests.cs
From https://github.com/octokit/webhooks.net/pull/742
----
> StringEnum small additions
